# -*- coding: utf-8 -*-
"""추천시스템.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15Yv6NiKRKrL7XqpaNuCpbTPd-ay_WxwE
"""

import pandas as pd
import numpy as np
from numpy import dot
from numpy.linalg import norm
from sklearn.preprocessing import LabelEncoder


def cos_sim(A, B):
  return dot(A, B)/(norm(A)*norm(B))

def Recomand(result_item_detail_new,result_cody_detail,result_style,input_list, le2, le):
#각 아이템에 대한 설명에서 카테고리와 색깔이 string으로 되어있으면 모델에 돌리기 힘들기때문에 각기 다른 labelencoder로 정수형태로 바꾸어 본다

#이는 각 label encoding 의 결과이다
#le.classes_, le2.classes_
# array ['가방', '기구/용품/장비', '디지털/테크', '모자', '바지', '상의', '생활/취미/예술',
#        '선글라스/안경테', '속옷', '스니커즈', '스커트', '스포츠잡화', '시계', '신발', '아우터',
#        '액세서리', '양말/레그웨어', '여성 가방', '주얼리', '책/음악/티켓', '하의'],
# array ['beige', 'brown', 'cream', 'grey', 'mint', 'navy', 'not shown','white', '카리나 착용 빅볼청키 다이아 모노그램 B D.Beige']

#cosine 유사도를 구하기 위한 코사인 유사도 식이 있는 코드이다



  #이는 예시 파일이다. 예시로 상의카테고리에 navy옷을 업로드 했다고 하면
  new_item = [0,0] #상의, navy
  new_item[0] = int(le.transform([input_list[0]]))
  new_item[1] = int(le2.transform([input_list[1]]))
  index = result_item_detail_new[result_item_detail_new[['카테고리', '색깔']] == new_item][['카테고리', '색깔']].dropna().index
  #이 코드를 실행하면 그 상의 navy 인 옷들의 사이트, 즉 기본키가 출력이 된다
  #result_item_detail_new.loc[index]['사이트']

  #고로 밑의 코드를 실행하면 그 옷들의 사이트의 기본키를 활용하여, 그 기본키가 존재하는 코디들의 사이트, 기본키를 가져온다. 즉 외래키를 통해서 코디의 기본키를 찾는 것이다
  total_list= []
  for i in result_item_detail_new.loc[index]['사이트']:
    for a, j in result_cody_detail.iterrows():
      if i in list(j):
        #print(j[0])
        total_list.append(j)

  #print(total_list)      

  lst = []
    #이 코드를 이용해서 어떤 사진이 출력되었는지 확인할 수 있다. 
  for i in total_list:
    #image_first = result_style[result_style['사이트'] == i[0]]['image'].to_string()
    
    for k in result_style.iterrows():
      if i[0] ==k[1][1]:
        lst.append([k[1][1], k[1][0]])
        print(lst)
  return lst
